apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: ns-b
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c", "while true; do sleep 3600; done" ]

# 然后，尝试在Pod-a中ping Pod-b：
#  kubectl exec -it pod-a -n ns-a -- /bin/sh
#  ping pod-b.ns-b