apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 3  # 确保有3个Pod副本
  selector:
    app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
#          image: nginx
          image: harbor.systeminfos.com/library/nginx:1.25.1
          ports:
            - containerPort: 80