apiVersion: v1
kind: PersistentVolume
metadata:
  name: test3
  labels:
    type: test
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/k8s"
    server: 172.16.166.138
    readOnly: false

